### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by phndiaye** [upfluence/oss-components#50]
This is a quick roadmap for what should be achieved in terms of documentation in OSS related projects (OSS and OSS-Component).

#### In https://github.com/upfluence/oss-components

* Get Started
  * Installation Steps

* Components
  * Progress Bar
  * Modals (Current Status: In ember-upf-utils)
    * Add a title option to the component so we don't need to write the boilerplate anymore
    * Add support for backdrop click (handled by the `closeAction`)
  * Tooltips (Current Status: Mixin written in ember-upf-utils)
  * Toggle Switch
  * Button Groups

#### In https://github.com/upfluence/oss

* Introduction
  * Resources about BEM
* Core
  * Variables
    * Font Stacks
    * Spacing
    * Brand Colors (facebook, twitter, etc.)
* Base
  * Buttons
    * On Dark Background (the `upf-btn--dark-bg`modifier)
    * Destructive
    * Social Medias (branded buttons for social medias)
     * With right icons
  * Checkboxes
* Utility Classes
  * Text Colors (both default and for contrast)
  * Text Style (bold, normal, italic, etc.)
  * Text Size
  * Spacing (margin and padding)

**Comment by leanminmachine** [comment]
WIP: Going thru the codebase to see what has not been mentioned above, and making a plan to document it.

**In https://github.com/upfluence/oss:**
- Base
   - Cards
   - Checkbox
    - Datatable
    - Input
    - Link
   - Loading
    - Nav
    - Notification
   - Progress bar
   - Tags
   - Toast
   - Transitions
- Core
   - Upf icons

**In https://github.com/upfluence/oss-components:**
- Components 
   - Upf table
   - Destructive button
   - Expanding search
   - Input wrapper
   - Loading button
   - Loading state
   - Radio button
   - Standard stat
   - Summernote
   - Upf-card
   - Upf checkbox
   - Upf icon
   - Upf image 

**Between oss and oss-components:**
